[package]
name = "orml-tokens"
version = "0.0.1"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate.git", default-features = false }
paint-support = { package = "paint-support", git = "https://github.com/paritytech/substrate.git", default-features = false }
paint-system = { package = "paint-system", git = "https://github.com/paritytech/substrate.git", default-features = false }
runtime-io = { package = "sr-io", git = "https://github.com/paritytech/substrate.git", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate.git", default-features = false }

traits = { package = "orml-traits", path = "../traits", default-features = false }
utilities = { package = "orml-utilities", path = "../utilities", default-features = false }

[dev-dependencies]
primitives = { package = "substrate-primitives",  git = "https://github.com/paritytech/substrate.git", default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sr-primitives/std",
	"paint-support/std",
	"paint-system/std",
	"rstd/std",
	"traits/std",
	"utilities/std",
	"runtime-io/std",
]
